version: '3.9'
services:
  app:
    build: .
    volumes:
      - media_data:/app/media
      - sql_data:/var/lib/mysql
    ports:
      - 8000:80
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  media_data:
  sql_data:
  